name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['10.0.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: 'true'

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'
          
      - name: Restore and build (publish)
        run: dotnet publish /p:Configuration=Release /p:TargetFramework=net8.0 /p:PublishProfile=FolderProfile
      
      - name: Pack published files
        run: |
          cd plugin_Kinect360NiTE/bin/Release/Publish
          7z a plugin_Kinect360NiTE.zip *
        
      - name: Upload plugin artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "ame2-latest"
          prerelease: true
          title: "plugin_Kinect360NiTE Build Artifact"
          files: |
            ./plugin_Kinect360NiTE/bin/Release/Publish/plugin_Kinect360NiTE.zip
            ./external/manifest.json
